/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_wjdiankong_bsdiff_PatchUtils */

#ifndef _Included_cn_wjdiankong_bsdiff_PatchUtils
#define _Included_cn_wjdiankong_bsdiff_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_wjdiankong_bsdiff_PatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_wjdiankong_bsdiff_PatchUtils_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
